branches:
  only:
    - master
    - internal

build: false

environment:
  TEST_NWB_FILES: skip
  TEST_OBSERVATORY_EXPERIMENT_PLOTS_DATA: skip
  TEST_API_ENDPOINT: http://api.brain-map.org 
  TEST_COMPLETE: "false"
  matrix:
    - MINICONDA: "C:\\Miniconda-x64"
      PYTHON: 2.7
    - MINICONDA: "C:\\Miniconda36-x64"
      PYTHON: 3.6
    - MINICONDA: "C:\\Miniconda37-x64"
      PYTHON: 3.7

install:
  - set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python=%PYTHON% pip
  - activate test-environment
  - conda install statsmodels
  - pip install Pillow
  - if %PYTHON% == 2.7 conda install -c conda-forge scikit-image
  - if %PYTHON% == 2.7 pip install SimpleITK==1.1.0
  - pip install codecov
  - pip install -r test_requirements.txt
  - pip install .

test_script:
  - py.test --cov=allensdk
  - codecov
