name: Notebooks
on:
  push:
    branches:
      - master
jobs:
  run_notebooks:
    name: Notebook runner
    strategy:
      matrix:
        python-version: ["3.13"]
      fail-fast: false
    runs-on: ubuntu-latest-8x
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Install
        run: |
          pip install -e ".[dev,notebooks]"
          ipython kernel install --name "python3" --user
      - name: Run notebooks
        run: |
          python -m allensdk.internal.notebooks.execute_notebooks \
            --notebooks_dir doc_template/examples_root/examples/nb \
            --skip_notebooks behavior_ophys_session.ipynb
      - name: Commit and push updated notebooks
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update notebooks
          push_options: --force
          file_pattern: '*.ipynb'
